      SUBROUTINE METRIC(ALAT,BIJ,IA2)
      IMPLICIT REAL*8 (A-H,O-Z)
      DIMENSION ALAT(3,3),BIJ(3,3)
C
      RADDEG=180.D0/(4.D0*ATAN(1.D0))
C
C     TRANSFORM THE LATTICE VECTORS IN A FORM THAT IS
C     APPROPRIATE TO THE VOLCAL PROGRAM! IN OTHER WORDS
C     CALCULATE THE LENGTH AND ANGLES FROM BIJ!
C
C     FIRST CALCULATE THE METRIC-TENSOR FOR THE CONVERSION
C     OF LENGTH FROM THE LATTICE SYSTEM TO THE CARTESIAN
C     SYSTEM!
C
      DO 50, II=1, 3
        DO 55, IK=1, 3
          BIJ(II,IK)=0.D0
          DO 60, IL=1, 3
            BIJ(II,IK)=BIJ(II,IK)+ALAT(IL,II)*ALAT(IL,IK)
60        CONTINUE
55      CONTINUE
50    CONTINUE
C
C     REMINDER ON THE TERMS USED IN THIS NOTATION:
C           A,B,C LENGTH OF THE LATTICE-VECTORS
C           ALPHA=ANGLE(B,C)
C           BETA =ANGLE(C,A)
C           GAMMA=ANGLE(A,B)
C
        A=SQRT(BIJ(1,1))
        B=SQRT(BIJ(2,2))
        C=SQRT(BIJ(3,3))
C
        ALPHA=ACOS(BIJ(2,3)/(B*C))
        BETA=ACOS(BIJ(1,3)/(A*C))
        GAMMA=ACOS(BIJ(1,2)/(A*B))
C
C        WRITE(11,*)'TITLE!!!'
C        WRITE(*,1010)A,B,C,RADDEG*ALPHA,RADDEG*BETA,
C     1       RADDEG*GAMMA,IA2,0
C        WRITE(11,1010)A,B,C,RADDEG*ALPHA,RADDEG*BETA,
C     1       RADDEG*GAMMA,IA2,0
1010    FORMAT (6F12.7,2I4)
C
        RETURN
        END
 
